title: "Mi página web"
description: "Hola, soy un estudiante de maestría en matemáticas aplicadas y actualmente me encuentro aprendiendo computacion"
baseurl: ""
url: "https:://digitaldeviltapia.github.io"
theme: minima
